2022-03-14 14:30:35,657 INFO    MainThread:9548 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-14 14:30:35,657 INFO    MainThread:9548 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-14 14:30:35,658 INFO    MainThread:9548 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\logs\debug.log
2022-03-14 14:30:35,658 INFO    MainThread:9548 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\logs\debug-internal.log
2022-03-14 14:30:35,658 INFO    MainThread:9548 [wandb_init.py:init():404] calling init triggers
2022-03-14 14:30:35,672 INFO    MainThread:9548 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-14 14:30:35,672 INFO    MainThread:9548 [wandb_init.py:init():460] starting backend
2022-03-14 14:30:35,676 INFO    MainThread:9548 [backend.py:ensure_launched():216] starting backend process...
2022-03-14 14:30:35,676 INFO    MainThread:9548 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-14 14:30:35,677 INFO    BackendThr:9548 [internal.py:wandb_internal():90] W&B internal server running at pid: 9548, started at: 2022-03-14 14:30:35.676815
2022-03-14 14:30:35,677 INFO    MainThread:9548 [wandb_init.py:init():469] backend started and connected
2022-03-14 14:30:35,680 INFO    MainThread:9548 [wandb_init.py:init():533] updated telemetry
2022-03-14 14:30:35,682 INFO    WriterThread:9548 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\run-2sjmj13q.wandb
2022-03-14 14:30:35,740 INFO    MainThread:9548 [wandb_init.py:init():563] communicating current version
2022-03-14 14:30:35,936 INFO    MainThread:9548 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 14:30:35,938 INFO    MainThread:9548 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 14:30:36,433 INFO    MainThread:9548 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 14:30:36,456 INFO    SenderThread:9548 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files
2022-03-14 14:30:36,456 INFO    SenderThread:9548 [sender.py:_start_run_threads():807] run started: 2sjmj13q with start time 1647248435
2022-03-14 14:30:36,457 INFO    SenderThread:9548 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 14:30:37,440 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\conda-environment.yaml
2022-03-14 14:30:37,441 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\requirements.txt
2022-03-14 14:30:37,441 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\wandb-summary.json
2022-03-14 14:30:39,924 INFO    SenderThread:9548 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 14:30:39,944 INFO    MainThread:9548 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 14:30:39,946 INFO    MainThread:9548 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 14:30:39,946 INFO    MainThread:9548 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 14:30:39,949 INFO    MainThread:9548 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 14:30:39,949 INFO    MainThread:9548 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 14:30:40,457 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\conda-environment.yaml
2022-03-14 14:30:40,457 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log
2022-03-14 14:30:40,458 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\wandb-metadata.json
2022-03-14 14:30:41,190 INFO    Thread-22 :9548 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmpczr2ujvuwandb\3nyzx2tx-wandb-metadata.json
2022-03-14 14:30:42,474 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log
2022-03-14 14:30:44,229 WARNING MsgRouterThr:9548 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 14:30:44,229 INFO    MainThread:9548 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 14:30:44,230 INFO    MainThread:9548 [wandb_run.py:_restore():1752] restore
2022-03-14 14:30:44,501 INFO    Thread-17 :9548 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log
2022-03-14 14:30:44,983 INFO    WriterThread:9548 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\run-2sjmj13q.wandb
2022-03-14 14:30:44,983 INFO    SenderThread:9548 [sender.py:finish():1070] shutting down sender
2022-03-14 14:30:44,983 INFO    SenderThread:9548 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 14:30:45,513 INFO    SenderThread:9548 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log
2022-03-14 14:30:45,513 INFO    SenderThread:9548 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files
2022-03-14 14:30:45,514 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\conda-environment.yaml conda-environment.yaml
2022-03-14 14:30:45,514 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\config.yaml config.yaml
2022-03-14 14:30:45,515 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log output.log
2022-03-14 14:30:45,515 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\requirements.txt requirements.txt
2022-03-14 14:30:45,531 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\wandb-metadata.json wandb-metadata.json
2022-03-14 14:30:45,532 INFO    SenderThread:9548 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\wandb-summary.json wandb-summary.json
2022-03-14 14:30:45,536 INFO    SenderThread:9548 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 14:30:45,536 INFO    SenderThread:9548 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 14:30:46,620 INFO    Thread-33 :9548 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\wandb-summary.json
2022-03-14 14:30:46,637 INFO    Thread-32 :9548 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\requirements.txt
2022-03-14 14:30:46,637 INFO    Thread-31 :9548 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\output.log
2022-03-14 14:30:46,713 INFO    Thread-29 :9548 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\conda-environment.yaml
2022-03-14 14:30:46,715 INFO    Thread-30 :9548 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_143035-2sjmj13q\files\config.yaml
2022-03-14 14:30:47,446 ERROR   BackendThr:9548 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 14:30:50,057 INFO    MainThread:9548 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 14:30:50,167 INFO    MainThread:9548 [wandb_run.py:_restore():1752] restore
2022-03-14 14:30:50,238 INFO    MainThread:9548 [internal.py:handle_exit():77] Internal process exited
