2022-03-15 01:04:28,541 INFO    MainThread:16156 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-15 01:04:28,541 INFO    MainThread:16156 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-15 01:04:28,542 INFO    MainThread:16156 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\logs\debug.log
2022-03-15 01:04:28,542 INFO    MainThread:16156 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\logs\debug-internal.log
2022-03-15 01:04:28,542 INFO    MainThread:16156 [wandb_init.py:init():404] calling init triggers
2022-03-15 01:04:28,557 INFO    MainThread:16156 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-15 01:04:28,557 INFO    MainThread:16156 [wandb_init.py:init():460] starting backend
2022-03-15 01:04:28,561 INFO    MainThread:16156 [backend.py:ensure_launched():216] starting backend process...
2022-03-15 01:04:28,561 INFO    MainThread:16156 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-15 01:04:28,562 INFO    BackendThr:16156 [internal.py:wandb_internal():90] W&B internal server running at pid: 16156, started at: 2022-03-15 01:04:28.561701
2022-03-15 01:04:28,562 INFO    MainThread:16156 [wandb_init.py:init():469] backend started and connected
2022-03-15 01:04:28,564 INFO    MainThread:16156 [wandb_init.py:init():533] updated telemetry
2022-03-15 01:04:28,566 INFO    WriterThread:16156 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\run-5m6bnb14.wandb
2022-03-15 01:04:28,611 INFO    MainThread:16156 [wandb_init.py:init():563] communicating current version
2022-03-15 01:04:28,774 INFO    MainThread:16156 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-15 01:04:28,776 INFO    MainThread:16156 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-15 01:04:29,258 INFO    MainThread:16156 [wandb_init.py:init():606] starting run threads in backend
2022-03-15 01:04:29,264 INFO    SenderThread:16156 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files
2022-03-15 01:04:29,264 INFO    SenderThread:16156 [sender.py:_start_run_threads():807] run started: 5m6bnb14 with start time 1647286468
2022-03-15 01:04:29,265 INFO    SenderThread:16156 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-15 01:04:30,278 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\conda-environment.yaml
2022-03-15 01:04:30,279 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\wandb-summary.json
2022-03-15 01:04:30,279 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\requirements.txt
2022-03-15 01:04:31,663 INFO    SenderThread:16156 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-15 01:04:31,683 INFO    MainThread:16156 [wandb_run.py:_console_start():1810] atexit reg
2022-03-15 01:04:31,700 INFO    MainThread:16156 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-15 01:04:31,701 INFO    MainThread:16156 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-15 01:04:31,702 INFO    MainThread:16156 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-15 01:04:31,703 INFO    MainThread:16156 [wandb_init.py:init():633] run started, returning control to user process
2022-03-15 01:04:32,292 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\conda-environment.yaml
2022-03-15 01:04:32,292 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\wandb-metadata.json
2022-03-15 01:04:32,293 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\output.log
2022-03-15 01:04:33,017 INFO    Thread-22 :16156 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmpyqz28ov_wandb\14dc7b00-wandb-metadata.json
2022-03-15 01:04:34,298 INFO    Thread-17 :16156 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\output.log
2022-03-15 01:11:10,824 INFO    MainThread:16156 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-15 01:11:10,824 WARNING MsgRouterThr:16156 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-15 01:11:10,825 INFO    MainThread:16156 [wandb_run.py:_restore():1752] restore
2022-03-15 01:11:10,847 INFO    SenderThread:16156 [sender.py:finish():1070] shutting down sender
2022-03-15 01:11:10,847 INFO    SenderThread:16156 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-15 01:11:11,150 INFO    WriterThread:16156 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\run-5m6bnb14.wandb
2022-03-15 01:11:11,716 INFO    SenderThread:16156 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\output.log
2022-03-15 01:11:11,716 INFO    SenderThread:16156 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files
2022-03-15 01:11:11,717 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\conda-environment.yaml conda-environment.yaml
2022-03-15 01:11:11,717 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\config.yaml config.yaml
2022-03-15 01:11:11,718 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\output.log output.log
2022-03-15 01:11:11,727 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\requirements.txt requirements.txt
2022-03-15 01:11:11,728 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\wandb-metadata.json wandb-metadata.json
2022-03-15 01:11:11,731 INFO    SenderThread:16156 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\wandb-summary.json wandb-summary.json
2022-03-15 01:11:11,734 INFO    SenderThread:16156 [file_pusher.py:finish():177] shutting down file pusher
2022-03-15 01:11:11,734 INFO    SenderThread:16156 [file_pusher.py:join():182] waiting for file pusher
2022-03-15 01:11:12,867 INFO    Thread-32 :16156 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\output.log
2022-03-15 01:11:12,922 INFO    Thread-30 :16156 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\conda-environment.yaml
2022-03-15 01:11:12,939 INFO    Thread-31 :16156 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\config.yaml
2022-03-15 01:11:12,954 INFO    Thread-34 :16156 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\wandb-summary.json
2022-03-15 01:11:12,997 INFO    Thread-33 :16156 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220315_010428-5m6bnb14\files\requirements.txt
2022-03-15 01:11:13,592 ERROR   BackendThr:16156 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-15 01:11:16,266 INFO    MainThread:16156 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-15 01:11:16,375 INFO    MainThread:16156 [wandb_run.py:_restore():1752] restore
2022-03-15 01:11:16,401 INFO    MainThread:16156 [internal.py:handle_exit():77] Internal process exited
