2022-03-14 22:54:28,436 INFO    BackendThr:16280 [internal.py:wandb_internal():90] W&B internal server running at pid: 16280, started at: 2022-03-14 22:54:28.436399
2022-03-14 22:54:28,437 INFO    MainThread:16280 [wandb_init.py:init():469] backend started and connected
2022-03-14 22:54:28,437 DEBUG   MainThread:16280 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-03-14 22:54:28,439 INFO    MainThread:16280 [wandb_init.py:init():533] updated telemetry
2022-03-14 22:54:28,441 INFO    WriterThread:16280 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\run-1tbngd49.wandb
2022-03-14 22:54:28,443 DEBUG   SenderThread:16280 [sender.py:send():234] send: header
2022-03-14 22:54:28,488 INFO    MainThread:16280 [wandb_init.py:init():563] communicating current version
2022-03-14 22:54:28,489 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: check_version
2022-03-14 22:54:28,490 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: check_version
2022-03-14 22:54:28,623 INFO    MainThread:16280 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 22:54:28,624 INFO    MainThread:16280 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 22:54:28,625 DEBUG   SenderThread:16280 [sender.py:send():234] send: run
2022-03-14 22:54:28,993 INFO    MainThread:16280 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 22:54:28,994 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: run_start
2022-03-14 22:54:28,998 INFO    SenderThread:16280 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files
2022-03-14 22:54:28,998 INFO    SenderThread:16280 [sender.py:_start_run_threads():807] run started: 1tbngd49 with start time 1647278668
2022-03-14 22:54:28,998 DEBUG   SenderThread:16280 [sender.py:send():234] send: summary
2022-03-14 22:54:28,999 INFO    SenderThread:16280 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 22:54:29,013 DEBUG   HandlerThread:16280 [meta.py:__init__():40] meta init
2022-03-14 22:54:29,013 DEBUG   HandlerThread:16280 [meta.py:__init__():54] meta init done
2022-03-14 22:54:29,013 DEBUG   HandlerThread:16280 [meta.py:probe():214] probe
2022-03-14 22:54:29,027 DEBUG   HandlerThread:16280 [meta.py:_setup_git():204] setup git
2022-03-14 22:54:29,120 DEBUG   HandlerThread:16280 [meta.py:_setup_git():211] setup git done
2022-03-14 22:54:29,121 DEBUG   HandlerThread:16280 [meta.py:_save_pip():58] save pip
2022-03-14 22:54:29,121 DEBUG   HandlerThread:16280 [meta.py:_save_pip():72] save pip done
2022-03-14 22:54:29,121 DEBUG   HandlerThread:16280 [meta.py:_save_conda():79] save conda
2022-03-14 22:54:29,997 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt
2022-03-14 22:54:29,998 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:54:29,998 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json
2022-03-14 22:54:31,333 DEBUG   HandlerThread:16280 [meta.py:_save_conda():89] save conda done
2022-03-14 22:54:31,333 DEBUG   HandlerThread:16280 [meta.py:probe():252] probe done
2022-03-14 22:54:31,351 DEBUG   SenderThread:16280 [sender.py:send():234] send: files
2022-03-14 22:54:31,351 INFO    SenderThread:16280 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 22:54:31,368 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:54:31,368 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:54:31,369 INFO    MainThread:16280 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 22:54:31,371 INFO    MainThread:16280 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 22:54:31,371 INFO    MainThread:16280 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 22:54:31,373 INFO    MainThread:16280 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 22:54:31,373 INFO    MainThread:16280 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 22:54:32,006 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:54:32,006 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-metadata.json
2022-03-14 22:54:32,007 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:54:32,313 INFO    Thread-22 :16280 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmp2rptoqwawandb\tm2ki4ub-wandb-metadata.json
2022-03-14 22:54:34,034 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:54:36,047 INFO    Thread-17 :16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:54:46,739 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:54:46,740 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:55:00,304 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:55:02,548 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:55:02,549 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:55:17,919 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:55:17,920 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:55:33,280 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:55:33,280 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:55:33,622 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:55:48,639 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:55:48,640 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:56:04,008 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:56:04,009 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:56:06,928 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:56:19,399 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:56:19,400 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:56:34,769 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:56:34,770 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:56:40,201 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:56:50,134 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:56:50,135 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:57:05,499 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:57:05,500 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:57:13,447 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:57:20,869 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:57:20,870 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:57:36,250 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:57:36,250 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:57:46,671 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:57:52,243 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:57:52,244 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:58:07,625 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:58:07,626 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:58:19,916 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:58:23,009 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:58:23,010 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:58:38,383 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:58:38,384 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:58:53,214 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:58:53,750 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:58:53,751 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:59:09,126 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:59:09,126 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:59:24,502 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:59:24,503 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:59:26,474 DEBUG   SenderThread:16280 [sender.py:send():234] send: stats
2022-03-14 22:59:39,854 DEBUG   HandlerThread:16280 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 22:59:39,855 DEBUG   SenderThread:16280 [sender.py:send_request():248] send_request: stop_status
2022-03-14 22:59:43,777 WARNING MsgRouterThr:16280 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 22:59:43,934 INFO    MainThread:16280 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 22:59:43,935 INFO    MainThread:16280 [wandb_run.py:_restore():1752] restore
2022-03-14 22:59:44,244 INFO    SenderThread:16280 [sender.py:finish():1070] shutting down sender
2022-03-14 22:59:44,244 INFO    SenderThread:16280 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 22:59:44,277 INFO    SenderThread:16280 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:59:44,277 INFO    SenderThread:16280 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files
2022-03-14 22:59:44,278 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml conda-environment.yaml
2022-03-14 22:59:44,278 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\config.yaml config.yaml
2022-03-14 22:59:44,279 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log output.log
2022-03-14 22:59:44,288 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt requirements.txt
2022-03-14 22:59:44,290 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-metadata.json wandb-metadata.json
2022-03-14 22:59:44,296 INFO    SenderThread:16280 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json wandb-summary.json
2022-03-14 22:59:44,301 INFO    SenderThread:16280 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 22:59:44,302 INFO    SenderThread:16280 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 22:59:44,605 INFO    WriterThread:16280 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\run-1tbngd49.wandb
2022-03-14 22:59:45,252 INFO    Thread-33 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\requirements.txt
2022-03-14 22:59:45,259 INFO    Thread-30 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\conda-environment.yaml
2022-03-14 22:59:45,265 INFO    Thread-34 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\wandb-summary.json
2022-03-14 22:59:45,285 INFO    Thread-32 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\output.log
2022-03-14 22:59:45,296 INFO    Thread-31 :16280 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_225428-1tbngd49\files\config.yaml
2022-03-14 22:59:46,140 ERROR   BackendThr:16280 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 22:59:48,975 INFO    MainThread:16280 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 22:59:49,082 INFO    MainThread:16280 [wandb_run.py:_restore():1752] restore
2022-03-14 22:59:49,107 INFO    MainThread:16280 [internal.py:handle_exit():77] Internal process exited
